name: mingw-builder
on:
  workflow_dispatch:
    branches: [ master, stable* ]
  schedule:
    - cron: '30 5 * * SUN'

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run mingw build on ubuntu-latest"
    steps:
      - name: "Check out source"
        uses: actions/checkout@v4

      - name: "Prepare environment"
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -q -y \
            git \
            nasm \
            meson \
            cmake \
            ninja-build \
            mingw-w64 \
            mingw-w64-tools \
            binutils-mingw-w64

      - name: "Run mingw [shared] build..."
        run: |
          ./scripts/mingw.sh

      - name: "Run mingw [static] build..."
        run: |
          ./scripts/mingw.sh -c -s --clean-first

      # --- THIS IS THE ONLY THING I'VE ADDED ---
      - name: "Upload [static] Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: freerdp-windows-static-build-3.18.0
          path: install-static/
          if-no-files-found: error
          
